### ISSUE TITLE
Release v2.0.1

### ISSUE THREAD

**Issue by mdpiper** [TerrainBento/terrainbento#175]
@kbarnhart I'm ready to tag v2.0.1 and make a release. Would this be OK?

Also, post-release, I don't have permissions to upload to PyPI or conda-forge. Would you be able to help with this, please?

**Comment by kbarnhart** [comment]
@mdpiper sorry I missed this. yes, this is totally fine with me. I'll try and add you as an admin on pypi and conda-forge now.

**Comment by kbarnhart** [comment]
@mdpiper what is your pypi username?

**Comment by mdpiper** [comment]
@kbarnhart Same as my GitHub username!

**Comment by kbarnhart** [comment]
@mdpiper I think you should now have pypi and conda-forge access. let me know if it appears otherwise to you. thanks again for working on maintenance for this project :tada:

**Comment by mdpiper** [comment]
Thank you, @kbarnhart!

**Comment by mdpiper** [comment]
Closed with https://github.com/TerrainBento/terrainbento/commit/cbf9d93f333e5cb3307613f687c2f2106511d068.
