### ISSUE TITLE
Finalize model documentation

### ISSUE THREAD

**Issue by kbarnhart** [TerrainBento/terrainbento#38]
@Glader011235 @cmshobe @gregtucker 

This commit is intended to provide a guide to splitting up finalizing the documentation and testing of the remaining model program files. 

Crib notes: Make the docstrings look like model 000's. Add tests for each model like those for model 000 in the test folder. Ideally we get 100% coverage for EVERYTHING!

Some recent changes: We no longer use `nose`. This means that you can't type `from nose.tools import assert_raises`. Don't freak out you can do `import pytest` and then `pytest.raises()`. I've changed this everywhere in the existing tests already so you can take inspiration examples from _within terrainbento_ (but landlab still uses `nose`). Why did I do this... because `nose` isn't being maintained and its developers recommend using `py.test`.

This is what I propose to start:
1. Me: All Rock/Till models: (800/804, 802, 808, 810, 840, 842, A00, C00)
2. @cmshobe : Start with 002, 008/00C, 010, 018, 410
3. @Glader011235 : start with 040, 400, 440, CCC

I'd recommend that you do one or two, and then create a PR in case there is anything else to clarify. 

Still to be assigned:
The stochastic ones: 100/104, 102, 108, 110
the VSA ones: 200/204, 202, 208, 210, 300

@gregtucker will claim some of these when he can. 

I am **almost** done getting the Travis/Coveralls CI to work right. 🤞 I'll make a comment when that's done.

**Comment by kbarnhart** [comment]
FYI @cmshobe @Glader011235 you can commit directly into this repo instead of using a fork (like you do in landlab). 
This is because I added you as contributors to the repository.

**Comment by kbarnhart** [comment]
OK! Travis and Docs are all working. I'm nearly certain Coveralls is working. I'll test it and report back!

**Comment by cmshobe** [comment]
status update: I've done the documentation for 002, 008, 010, 018, and 410 (#56) so just need to do the tests next. @kbarnhart can you remind me what 00C is? Is this just some alternative parameterization of 008?

**Comment by kbarnhart** [comment]
Quick note. @gregtucker currently taking 100/104, 102, 108, 110

**Comment by kbarnhart** [comment]
current status:

Remaining for tests only:
808, 810, 840, 842, A00, C00 (assigned to me)
ErosionModel (assigned to me)
StochasticErosionModel (assigned to me)


Remaining for Docs and Tests:
100/104, 102, 108, 110 (assigned to @gregtucker)
012 (not yet assigned)
200/204, 202, 208, 210, 300 (not yet assigned)

**Comment by kbarnhart** [comment]
Another update on the status of remaining models:

All done (nice job everyone!)

* 000, 002, 008, 018, 040, 400, 410, 440, 800, 802, and C00

Assigned to me:
* 010 and 410 need small tweaks to permit thresholds to be passed successfully. 
* End member analytical unit tests for 808, 810, 840, 842, A00, C00 
* Finalize ErosionModel and StochasticErosionModel tests
* Documentation and end member analytical tests for 300 

Assigned to @Glader011235 
* End member analytical tests for 200, 202, 208, 210, 300. Wait until PR #63 is merged and then feel free to start. 

Assigned to @gregtucker 
* Documentation and end member analytical tests for 100, 102, 108, 110. You'll want to update from #63 once its merged.

**Comment by cmshobe** [comment]
since nothing is assigned to me (much appreciated!) and I'll be MIA for the
next week, I will plan to finish whatever Rachel has left when she leaves
for Alaska.

**Comment by kbarnhart** [comment]
@cmshobe that is a great plan!
